account_id = "1e1b04d71f7d0f223bc1f2af2a56bac9"
compatibility_date = "2022-09-22"
main = "./src/index.js"
name = "atomic-url"

kv_namespaces = [
  {binding = "URL_DB", id = "ffe1778b6dcb4067b65d6f56ca092246", preview_id = "5a0d0e8cc73d4faa8d945865bd353ab5"},
]
workers_dev = true

[vars]
URL_CACHE = "apiCache" 
URL_EXPIRATION_TTL = 3600 # seconds

[dev]
ip = "0.0.0.0"
local_protocol = "http"
port = 8787
upstream_protocol = "https"

[env.staging]
kv_namespaces = [
  {binding = "URL_DB", id = "ffe1778b6dcb4067b65d6f56ca092246"},
]
name = "atomic-url-staging"
workers_dev = true
[env.staging.vars]
URL_CACHE = "apiCache" 
URL_EXPIRATION_TTL = 3600 # seconds

[env.production]
kv_namespaces = [
  {binding = "URL_DB", id = "249d3959e7154972ae483c57c6feb68c"},
]
name = "atomic-url"
route = "short.qianzhu.me/*"
workers_dev = false
[env.production.vars]
URL_CACHE = "apiCache" 
URL_EXPIRATION_TTL = 3600 # seconds
